from checkpoint_schedules import HRevolve

from .translation import translation

__all__ = \
    [
        "HRevolveCheckpointSchedule"
    ]


class HRevolveCheckpointSchedule(translation(HRevolve)):
    """An H-Revolve checkpointing schedule.

    Converts from schedules as generated by the H-Revolve library, for the
    case of two storage levels: RAM and disk.

    Offline, one adjoint calculation permitted.

    :arg max_n: The number of forward steps in the initial forward calculation.
    :arg snapshots_in_ram: The maximum number of forward restart checkpoints
        to store in memory.
    :arg snapshots_on_disk: The maximum number of forward restart checkpoints
        to store on disk.
    :arg wd: The write cost associated with saving a forward restart checkpoint
        to disk.
    :arg rd: The read cost associated with loading a forward restart checkpoint
        from disk.
    :arg uf: The cost of advancing the forward one step.
    :arg bf: The cost of advancing the forward one step, storing non-linear
        dependency data, and then advancing the adjoint over that step.

    The argument names `snaps_in_ram` and `snaps_on_disk` originate from the
    corresponding arguments for the `dolfin_adjoint.solving.adj_checkpointing`
    function in dolfin-adjoint (see e.g. version 2017.1.0).
    """

    def __init__(self, max_n, snapshots_in_ram, snapshots_on_disk, *,
                 wd=0.1, rd=0.1, uf=1.0, ub=2.0):
        super().__init__(
            max_n, snapshots_in_ram, snapshots_on_disk,
            uf=uf, ub=ub, wd=wd, rd=rd)
