name: test-tlm_adjoint-fenics

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    env:
      OMP_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: 'tlm_adjoint'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install flake8 python3-dolfin python3-h5py python3-numpy python3-pytest python3-pytest-timeout python3-pytest-xdist python3-scipy python3-sympy
      - name: Lint
        run: |
          cd tlm_adjoint
          flake8
      - name: Run tests
        run: |
          cd tlm_adjoint
          python3 -m pytest -v tests/base tests/checkpoint_schedules tests/fenics -n 4 --timeout=300 --timeout-method=thread
