name: test-tlm_adjoint-fenics

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      OMP_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          path: 'tlm_adjoint'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-dolfin python3-h5py python3-numpy python3-pytest python3-scipy
      - name: Run tests
        run: |
          cd tlm_adjoint
          pytest-3 -v tests/fenics
